In [1]:
import torch

### 초기화를 하지 않은 비어있는 8x4 matrix를 만들어 보세요

In [2]:
x = torch.empty(8, 4)
print(x.shape)

torch.Size([8, 4])


In [2]:
x = torch.empty(8, 4)
print(x)

tensor([[1.9208e+31, 7.1538e+22, 7.7764e+31, 7.1441e+31],
        [1.0899e+27, 3.1040e+27, 1.6931e+22, 2.0283e-19],
        [1.9432e-19, 1.8068e-19, 1.9206e+31, 2.7523e+23],
        [4.2322e+21, 2.8068e+20, 8.4006e-33, 1.7554e+25],
        [2.9602e+29, 7.1447e+31, 2.0196e-19, 1.2414e+28],
        [1.1839e+22, 6.8002e+22, 7.5551e+31, 1.0947e+27],
        [6.6532e-33, 4.3612e+27, 1.8177e+31, 6.6554e-33],
        [1.3563e-19, 1.6114e-19, 1.6020e-19, 4.4721e+21]])


# Note

torch.empty를 하면 값이 들어있지만 명시적인 값을 포함하지는 않는다. \
즉 당시 메모리에 할당되어 있던 값들이 들어가게 된다.

### 평균 5 표준편차 0.5로 초기화된 8x4 matrix를 만들어 보세요

In [3]:
x = torch.empty(8, 4).normal_(mean=5, std=0.5)
print(x)

tensor([[4.5150, 5.1500, 4.6943, 5.6825],
        [4.3610, 3.9612, 5.3652, 5.4946],
        [4.3496, 5.3495, 4.8267, 5.1166],
        [4.1521, 5.0385, 5.0090, 5.7111],
        [3.0722, 5.3551, 4.6422, 5.0723],
        [3.6937, 4.8502, 4.7636, 4.3589],
        [4.9427, 4.6512, 4.7024, 5.1892],
        [5.8472, 5.1168, 4.8032, 4.3172]])


### 평균 0 표준편차 1로 초기화된 8x4 matrix를 만들어 보세요

In [4]:
x = torch.empty(8, 4).normal_(mean=0, std=1)
print(x)

tensor([[-0.0039,  1.0035, -1.1693,  0.8994],
        [ 0.5585,  0.7548,  1.4745, -0.2823],
        [-0.8771,  1.0778,  1.6641,  1.0259],
        [-1.0090,  1.0915, -0.5237, -0.6970],
        [-0.2477, -0.1297, -0.6466,  0.5858],
        [-0.0740,  0.1176, -0.9773,  2.0920],
        [-0.5181, -1.1684,  0.5327, -1.6922],
        [-0.3953, -1.7849, -0.6660,  0.7235]])


In [5]:
x = torch.randn(8, 4)
print(x)

tensor([[-2.1958, -1.0537, -0.2865, -1.9334],
        [ 1.0008, -0.6228,  0.8290,  2.3613],
        [-0.3583,  0.2696, -0.0111, -0.4043],
        [-0.5755, -0.9351,  1.3290, -0.6095],
        [ 0.7900, -0.0737, -2.0427,  1.1189],
        [-0.9315, -0.1332, -0.3986, -1.1409],
        [-0.3407,  1.0172,  0.3098,  0.4418],
        [-0.5439, -0.9579, -0.9243, -1.8234]])


### 0으로 초기화된 5x5 matrix를 만들어 보세요

In [6]:
x = torch.zeros(5, 5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


### list [[2,3],[4,4]]를 tensor로 변경해 보세요

In [7]:
x = list([[2,3],[4,4]])

In [8]:
x = torch.tensor(x)
print(x)

tensor([[2, 3],
        [4, 4]])


### 1로 초기화된 7x4 matrix를 만들어 보세요

In [3]:
x = torch.ones(7, 4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### torch.randn을 이용하여 float 타입의 5x5 matrix를 만들어 보세요

In [4]:
x = torch.randn(5, 5, dtype=torch.float)
print(x)

tensor([[ 2.0919, -1.2152, -0.5937, -1.2268,  0.2094],
        [-0.1619,  1.2171, -1.1337,  1.0146, -0.5983],
        [-2.6574,  0.7220, -1.3212, -0.2555,  0.3813],
        [ 0.9597,  1.5991,  0.0416, -1.1972, -1.4226],
        [-0.4071, -2.0633, -0.3227,  0.1044, -0.6463]])


### torch.ones를 이용하여 long 타입의 5x5 mtrix를 만들어 보세요

In [8]:
x = torch.ones(5, 5, dtype=torch.long)
print(x)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])


### torch.randn을 이용하여 [100, 50] 2차원 matrix를 만들어 보세요

In [5]:
x = torch.randn(100, 50)
print(x.shape)

torch.Size([100, 50])


In [29]:
x = torch.randn(100, 50)
print(x.shape)

torch.Size([100, 50])


In [ ]:
#위에서 만든 [100, 20] matirx로 for문을 이용하여 [100] matrix 20개를 출력해 보세요

### torch.randn를 이용하여 [100, 50, 20] 3차원 matrix를 만들어 보세요

In [7]:
x = torch.randn(100, 50, 20)
print(x.shape)

torch.Size([100, 50, 20])


In [ ]:
100,50

In [25]:
x = torch.randn(2, 30, 20, 10)

In [27]:
x[2,:,:,:]

IndexError: index 2 is out of bounds for dimension 0 with size 2

In [11]:
x = torch.randn(100, 50, 20)
print(x.shape)

torch.Size([100, 50, 20])


### 위에서 만든 [100,50,20] matrix로 for문을 이용하여 [100, 20] matrix 50개를 출력해 보세요

In [13]:
for i in range(x.shape[1]):
    print(x[:,i,:].shape)

torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size([100, 20])
torch.Size

### 위에서 만든 [100,50,20]로 for문을 이용하여 [50, 20] matrix 100개를 출력해 보세요

In [14]:
for i in range(x.shape[0]):
    print(x[i,:,:].shape)

torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([50, 20])
torch.Size([5

### 위에서 만든 [100,50,20]로 for문을 이용하여 [100, 50] matrix 20개를 출력해 보세요

In [16]:
for i in range(x.shape[2]):
    print(x[:,:,i].shape)

torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])
torch.Size([100, 50])


### [30, 20] matrx를 만든 후 torch.randn_like를 이용하여 같은 shape의 matrix를 만들어 보세요

In [17]:
x = torch.randn(30, 20)

In [19]:
y = torch.randn_like(x)
print(y.shape)

torch.Size([30, 20])


# operations

In [23]:
x = torch.randn(5, 3)
y = torch.randn(5, 3)

**case 1**

In [24]:
z = x + y
print(z)

tensor([[-1.5494e+00,  9.0486e-01,  5.4884e-01],
        [-2.0742e+00, -2.8472e-01, -8.2462e-01],
        [ 1.3342e+00,  9.2211e-01, -1.1268e+00],
        [ 1.3952e+00, -1.0791e+00,  2.9247e+00],
        [-1.3841e-03, -4.5444e-01,  1.5352e+00]])


**case 2**

In [26]:
z = torch.add(x, y)
print(z)

tensor([[-1.5494e+00,  9.0486e-01,  5.4884e-01],
        [-2.0742e+00, -2.8472e-01, -8.2462e-01],
        [ 1.3342e+00,  9.2211e-01, -1.1268e+00],
        [ 1.3952e+00, -1.0791e+00,  2.9247e+00],
        [-1.3841e-03, -4.5444e-01,  1.5352e+00]])


**case 3**

In [27]:
z = torch.empty(5, 3)
torch.add(x, y, out=z)
print(z)

tensor([[-1.5494e+00,  9.0486e-01,  5.4884e-01],
        [-2.0742e+00, -2.8472e-01, -8.2462e-01],
        [ 1.3342e+00,  9.2211e-01, -1.1268e+00],
        [ 1.3952e+00, -1.0791e+00,  2.9247e+00],
        [-1.3841e-03, -4.5444e-01,  1.5352e+00]])


**case 3**

In [28]:
y.add_(x)
print(y)

tensor([[-1.5494e+00,  9.0486e-01,  5.4884e-01],
        [-2.0742e+00, -2.8472e-01, -8.2462e-01],
        [ 1.3342e+00,  9.2211e-01, -1.1268e+00],
        [ 1.3952e+00, -1.0791e+00,  2.9247e+00],
        [-1.3841e-03, -4.5444e-01,  1.5352e+00]])


# Numpy Bridge

In [41]:
a = torch.randn(3, 4)
print(a.shape)

torch.Size([3, 4])


In [42]:
b = a.numpy()
print(b.shape)

(3, 4)


# CUDA 사용하기

GPU를 이용하여 딥러닝을 학습하기 위해서는 데이터를 GPU로 전송해줘야 한다. \
pytorch에서는 간다하게 GPU연산을 할 수 있도록 함수를 제공해준다.

In [43]:
print(torch.cuda.is_available())

False


In [44]:
device = torch.device('cuda')