In [1]:
import torch
import torch.nn as nn

class LogisticRegression(nn.Module):
    def __init__(self, input_size, output_size):
        super(LogisticRegression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, X):
        output = self.linear(X)
        output = self.sigmoid(output)
        return output

model = LogisticRegression(2, 1)

# AND

In [2]:
x = [[0, 0], [0, 1], [1, 0], [1, 1]]
y = [[[0], [0], [0], [1]]]

x = torch.tensor(x, dtype=torch.float)
y = torch.tensor(y, dtype=torch.float)

In [11]:
import torch
import torch.nn as nn

class LogisticRegression(nn.Module):
    def __init__(self, input_size, output_size):
        print('초기화')
        super(LogisticRegression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, X):
        #print('입력')
        output = self.linear(X)
        output = self.sigmoid(output)
        return output

model = LogisticRegression(2, 1)

초기화


In [ ]:
def __call__

In [13]:
criterion = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

epochs = 100000
total = 0
correct = 0
model.train()
for epoch in range(epochs):
    prediction = model(x)
    print(prediction)
    loss = criterion(prediction, y)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if epoch % 10000 == 0:
        print(f'[Epoch:{epoch}/{epochs}] Loss: {round(loss.item(), 4)}')
    

입력
tensor([[0.4928],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
[Epoch:0/100000] Loss: 0.6932
입력
tensor([[0.4928],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4928],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4928],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4928],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4928],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4928],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4928],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4928],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4928],
        [0.5002],
    

입력
tensor([[0.4929],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4929],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4929],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4929],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4929],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4929],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4929],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4929],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4929],
        [0.5002],
        [0.4976],
        [0.5049]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4929],
        [0.5002],
        [0.4976],
        [0.5049]

입력
tensor([[0.4929],
        [0.5002],
        [0.4976],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5002],
        [0.4976],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5002],
        [0.4976],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5002],
        [0.4976],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5002],
        [0.4976],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5002],
        [0.4976],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5002],
        [0.4976],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5002],
        [0.4976],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5002],
        [0.4976],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5002],
        [0.4976],
        [0.5048]

tensor([[0.4930],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4930],
        [0.5001],
        [0.4977],
        [0.5048]], 

tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5048]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5048]], 

입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]

입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4931],
        [0.5001],
        [0.4977],
        [0.5047]

입력
tensor([[0.4932],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4977],
        [0.5047]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4977],
        [0.5047]

입력
tensor([[0.4932],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4932],
        [0.5001],
        [0.4978],
        [0.5046]

입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]

tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4933],
        [0.5001],
        [0.4978],
        [0.5046]], 

tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], 

tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4934],
        [0.5001],
        [0.4978],
        [0.5045]], 

tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5045]], 

tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5045]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4935],
        [0.5001],
        [0.4979],
        [0.5044]], 

tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], 

입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]

tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4936],
        [0.5001],
        [0.4979],
        [0.5044]], 

tensor([[0.4937],
        [0.5001],
        [0.4979],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4979],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4979],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4979],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4979],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4979],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4979],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4979],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4979],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4979],
        [0.5043]], 

입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]

입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4937],
        [0.5001],
        [0.4980],
        [0.5043]

tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5043]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5043]], 

tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5001],
        [0.4980],
        [0.5042]], 

입력
tensor([[0.4938],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4938],
        [0.5000],
        [0.4980],
        [0.5042]

tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], 

입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4939],
        [0.5000],
        [0.4980],
        [0.5042]

tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], 

입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]

입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4940],
        [0.5000],
        [0.4981],
        [0.5041]

tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5041]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5041]], 

입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]

입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4941],
        [0.5000],
        [0.4981],
        [0.5040]

입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]

tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], 

입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4942],
        [0.5000],
        [0.4982],
        [0.5040]

tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], 

tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], 

입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4943],
        [0.5000],
        [0.4982],
        [0.5039]

tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], 

tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4982],
        [0.5039]], 

입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]

tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4944],
        [0.5000],
        [0.4983],
        [0.5038]], 

tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], 

tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], 

입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4945],
        [0.5000],
        [0.4983],
        [0.5038]

입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]

tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], 

tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], 

tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4946],
        [0.5000],
        [0.4983],
        [0.5037]], 

tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5037]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5037]], 

tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], 

tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4947],
        [0.5000],
        [0.4984],
        [0.5036]], 

입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]

tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5036]], 

입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4948],
        [0.5000],
        [0.4984],
        [0.5035]

tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], 

tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.5000],
        [0.4984],
        [0.5035]], 

tensor([[0.4949],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4949],
        [0.4999],
        [0.4985],
        [0.5035]], 

tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5035]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5035]], 

tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], 

입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4950],
        [0.4999],
        [0.4985],
        [0.5034]

입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]

입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5034]

tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4951],
        [0.4999],
        [0.4985],
        [0.5033]], 

입력
tensor([[0.4952],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4985],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4985],
        [0.5033]

tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], 

tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], 

tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4952],
        [0.4999],
        [0.4986],
        [0.5033]], 

tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], 

tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], 

tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4953],
        [0.4999],
        [0.4986],
        [0.5032]], 

입력
tensor([[0.4954],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4954],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4954],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4954],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4954],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4954],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4954],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4954],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4954],
        [0.4999],
        [0.4986],
        [0.5032]], grad_fn=<SigmoidBackward>)
입력
tensor([[0.4954],
        [0.4999],
        [0.4986],
        [0.5032]

KeyboardInterrupt: 

# OR

In [5]:
x = [[0, 0], [0, 1], [1, 0], [1, 1]]
y = [[[0], [1], [1], [1]]]

x = torch.tensor(x, dtype=torch.float)
y = torch.tensor(y, dtype=torch.float)

In [6]:
import torch
import torch.nn as nn

class LogisticRegression(nn.Module):
    def __init__(self, input_size, output_size):
        super(LogisticRegression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, X):
        output = self.linear(X)
        output = self.sigmoid(output)
        return output

model = LogisticRegression(2, 1)

In [7]:
criterion = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

epochs = 100000
total = 0
correct = 0
model.train()
for epoch in range(epochs):
    prediction = model(x)
    loss = criterion(prediction, y)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if epoch % 10000 == 0:
        print(f'[Epoch:{epoch}/{epochs}] Loss: {round(loss.item(), 4)}')
    

[Epoch:0/100000] Loss: 0.5403
[Epoch:10000/100000] Loss: 0.3606
[Epoch:20000/100000] Loss: 0.2787
[Epoch:30000/100000] Loss: 0.2253
[Epoch:40000/100000] Loss: 0.1881
[Epoch:50000/100000] Loss: 0.161
[Epoch:60000/100000] Loss: 0.1403
[Epoch:70000/100000] Loss: 0.1241
[Epoch:80000/100000] Loss: 0.1111
[Epoch:90000/100000] Loss: 0.1004


# XOR

In [8]:
x = [[0, 0], [0, 1], [1, 0], [1, 1]]
y = [[[0], [1], [1], [0]]]

x = torch.tensor(x, dtype=torch.float)
y = torch.tensor(y, dtype=torch.float)

In [9]:
import torch
import torch.nn as nn

class LogisticRegression(nn.Module):
    def __init__(self, input_size, output_size):
        super(LogisticRegression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, X):
        output = self.linear(X)
        output = self.sigmoid(output)
        return output

model = LogisticRegression(2, 1)

In [10]:
criterion = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

epochs = 100000
total = 0
correct = 0
model.train()
for epoch in range(epochs):
    prediction = model(x)
    loss = criterion(prediction, y)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if epoch % 1000 == 0:
        print(f'[Epoch:{epoch}/{epochs}] Loss: {round(loss.item(), 4)}')
    

[Epoch:0/100000] Loss: 0.7166
[Epoch:1000/100000] Loss: 0.7078
[Epoch:2000/100000] Loss: 0.7033
[Epoch:3000/100000] Loss: 0.7008
[Epoch:4000/100000] Loss: 0.6993
[Epoch:5000/100000] Loss: 0.6983
[Epoch:6000/100000] Loss: 0.6976
[Epoch:7000/100000] Loss: 0.697
[Epoch:8000/100000] Loss: 0.6966
[Epoch:9000/100000] Loss: 0.6962
[Epoch:10000/100000] Loss: 0.6958
[Epoch:11000/100000] Loss: 0.6955
[Epoch:12000/100000] Loss: 0.6952
[Epoch:13000/100000] Loss: 0.695
[Epoch:14000/100000] Loss: 0.6948
[Epoch:15000/100000] Loss: 0.6946
[Epoch:16000/100000] Loss: 0.6944
[Epoch:17000/100000] Loss: 0.6943
[Epoch:18000/100000] Loss: 0.6941
[Epoch:19000/100000] Loss: 0.694
[Epoch:20000/100000] Loss: 0.6939
[Epoch:21000/100000] Loss: 0.6938
[Epoch:22000/100000] Loss: 0.6938
[Epoch:23000/100000] Loss: 0.6937
[Epoch:24000/100000] Loss: 0.6936
[Epoch:25000/100000] Loss: 0.6936
[Epoch:26000/100000] Loss: 0.6935
[Epoch:27000/100000] Loss: 0.6935
[Epoch:28000/100000] Loss: 0.6934
[Epoch:29000/100000] Loss: 0.6